Areas/Admin/Controllers/KinhNghiemController.cs
using Model.Dao;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TimKiemViecLam.Areas.Admin.Controllers
{
    public class KinhNghiemController : BaseController 
    {
        // GET: Admin/KinhNghiem
        public ActionResult Index()
        {
            var kinhNghiem = new KinhNghiemDAO();
            List<KinhNghiem> kinhNghiems = kinhNghiem.GetAllList();
            return View(kinhNghiems);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            new KinhNghiemDAO().xoaKinhNghiem(id);
            SetAlert("Xóa kinh nghiệm thành công", "success");
            return RedirectToAction("index");
        }
        [HttpPost]
        public ActionResult Create(KinhNghiem kinhNghiem)
        {
            if (ModelState.IsValid)
            {
                var dao = new KinhNghiemDAO();
                var check = dao.luuKinhNghiem(kinhNghiem);
                if (check == true)
                {
                    SetAlert("Thêm kinh nghiệm thành công", "success");
                    return RedirectToAction("index");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm mới không thành công");
                }
            }
            else
            {
                Response.Write("Không được để trống !");

            }

            return View("index");

        }
        [HttpPost]
        public ActionResult Edit(KinhNghiem kinhNghiem)
        {
            if (ModelState.IsValid)
            {
                var dao = new KinhNghiemDAO();
                var check = dao.suaKinhNghiem(kinhNghiem);
                if (check == true)
                {
                    SetAlert("Cập nhật kinh nghiệm thành công", "success");
                    return RedirectToAction("index");
                }
                else
                {
                    ModelState.AddModelError("", "Cập nhật không thành công");
                }
            }
            return View("index");

        }
    }
}

Areas/Admin/Views/KinhNghiem/Index.cshtml
@model List<Model.EF.KinhNghiem>


@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    QUẢN LÝ KINH NGHIỆM
}
@section jsFooter{
    <script src="~/Assets/Admin/libs/js/Area/Area.js"></script>
    <script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>

}

<div class="row">
    <!-- ============================================================== -->
    <!-- bordered table -->
    <!-- ============================================================== -->
    <div class="col-lg-8">
        <div class="card">
            <h4 class="card-header fas fa-coffee">&nbsp;Thêm Kinh Nghiệm</h4>
            <div class="card-body">
                @using (Html.BeginForm("Create", "KinhNghiem", FormMethod.Post))
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row">
                        @Html.Label("Tên Kinh Nghiệm *", new { @style = "padding-top:7px;" })
                        <div class="col">
                            <div class="input-group">
                                <input type="text" class="form-control " name="TenKinhNghiem" id="validationCustomUsername" placeholder="Kinh Nghiệm" aria-describedby="inputGroupPrepend" required>
                                <div class="invalid-feedback">
                                    Please choose a username.
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <button type="submit" id="btncreate" class="btn btn-primary active btn-sm"><i class="fas fa-plus"></i>&nbsp;Thêm mới</button>

                        </div>
                    </div>

                }
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="card">
            <h4 class="card-header fas fa-coffee">&nbsp; Quản Lý Kinh Nghiệm</h4>
            <div class="card-body">
                <table class="display" id="MyDataTable">
                    <thead>
                        <tr>
                            <th scope="col">STT</th>
                            <th scope="col">Danh sách kinh nghiệm</th>
                            <th scope="col">Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            var count = 1;
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            foreach (var item in Model)
                            {
                                <tr id="row_@item.ID_KinhNghiem">

                                    <td>@(count++)</td>

                                    @using (Html.BeginForm("Edit", "KinhNghiem", FormMethod.Post))
                                    {
                                <td>
                                    <span hidden>@item.TenKinhNghiem </span>
                                    <input type="hidden" name="ID_KinhNghiem" value="@item.ID_KinhNghiem" />
                                    <input type="text" value="@item.TenKinhNghiem" name="TenKinhNghiem" id="@item.TenKinhNghiem" class="col-lg-8" />
                                </td>
                                        <td>
                                            <button type="submit" class="btn btn-success btn-sm" data-id="capNhatArea"><i class="fas fa-edit"></i>&nbsp;Cập nhật</button>

                                            &nbsp;|&nbsp;
                                            <a class="btn btn-warning btn-sm" id="@item.ID_KinhNghiem" onclick="clik(@item.ID_KinhNghiem)" style="color:white;"><i class="fas fa-trash-alt"></i>&nbsp;Xóa</a>
                                          
                                        </td>
                                    }
                                </tr>
                              }
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#MyDataTable").DataTable();
    });
    function clik(id) {
        var iddelete =
            {
                id: id
            }
        var x = confirm("Bạn có muốn xóa bản ghi?");
        if (x) {
            $.ajax({
                url: '@Url.Action("Delete", "KinhNghiem")',
                type: 'POST',
                data: iddelete,
                OnComplete: function () {
                    OnComplete: "$('#row_" + id + "').remove()"
                },
                success: function () {
                    window.location.reload();
                },
                error: function () {
                    alert('error');
                }
            });
        }
    }
</script>